### ISSUE TITLE
Compiler throws error upon parsing blank line

### ISSUE THREAD

**Issue by Nes370** [kyperbelt/TTP_Compiler#1]
Currently if I leave a blank line in my source file, I receive:
`Error: "Invalid identifier on line:xx col:1"`
Where line xx corresponds to a blank line. I believe it would be more intuitive for the compiler to ignore the line of input if there are no instructions written. This allows for more flexible formatting. I am using Windows 10.

**Comment by kyperbelt** [comment]
@Nes370 I tried to reproduce the bug on linux but was unable to yield the same error (as of the latest commit). Going to switch to my windows environment and see if that changes anything.

**Comment by kyperbelt** [comment]
@Nes370 I think this might have been an issue with how windows handles line endings by adding a '\r' character as well. I have taken your advice and now it just skips all trivial characters like line endings and spaces. Let me know if there is still any issues. 

Appreciate the help!
